spring:
  datasource:
    url: ${DATASRC_URL_PROD}
    username: ${DATASRC_USER_PROD}
    password: ${DATASRC_PWD_PROD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    generate-ddl: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  sql:
    init:
      platform: postgres

############# Redis #############
  data:
    redis:
      host: redis
      port: 6379
      timeout: 6000

############# MongoDB #############
#  data:
#    mongodb:
#      uri: mongodb://localhost:27017/pruebamongo2025
#      database: pruebamongo2025
#      port: 27017
################################

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 2MB

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE